---
# This workflow integrates ShiftLeft NG SAST with GitHub
# Visit https://docs.shiftleft.io for help
name: QwietScan1

on:
  pull_request:
  push:
    branches:
      - main
      - master

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  Qwiet-Static-Analysis:
    runs-on: ubuntu-latest
    container: shiftleft/core:latest

    steps:
    - uses: actions/checkout@v4

    - name: Run sl analyze 1
      shell: bash
      run: |
        sl analyze --oss-project-dir . --verbose --wait --app "${GITHUB_REPOSITORY#*/}" .
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
